export const ques = [
  "What type of role are you interested in?",
  "Have you worked in the technology industry before?",
  "What are your core technical skills?",
  "What is your leadership experience?",
  "What programming languages are you proficient in?",
  "What is your level of experience with Blockchain Development?",
  "What is your preferred work location?",
  "What is your salary expectation for this role?",
  "Are you looking for a permanent or contract role?",
  "When are you available to start a new role?",
  "Do you have any experience with agile development methodologies?",
  "What is your experience with DevOps?",
  "What type of projects have you worked on in the past?",
  "How do you stay up-to-date with the latest technology trends?",
  "What is your level of experience with machine learning and artificial intelligence?",
  "Have you worked with any specific technology platforms or frameworks?",
  "Do you have any certifications related to technology?",
  "Are you willing to relocate for a new role?",
  "What is your level of experience with cloud computing?",
  "What is your level of experience with data analytics?",
  "What is your level of experience with cybersecurity?",
  "What is your level of experience with mobile app development?",
  "What is your level of experience with Cryptocurrency?",
  "What is your current salary/daily rate/hourly rate?",
  "What are your salary/daily rate/hourly rate expectations?",
];
